"""initial_schema

Revision ID: 14c7fe656937
Revises: 
Create Date: 2026-09-03 16:40:46.683189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c7fe656937'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('razorpay_account_id', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_account_id')
    )
    op.create_table('chargebacks',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('payment_source_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('chargeback_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_system', name='uix_chargeback_source')
    )
    op.create_table('invoices',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('invoice_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_system', name='uix_invoice_source')
    )
    op.create_table('ledger_entries',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('account_code', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('entry_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_system', name='uix_ledger_source')
    )
    op.create_table('orders',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('order_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_system', name='uix_order_source')
    )
    op.create_table('payments',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('order_source_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tax', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('payment_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_system', name='uix_payment_source')
    )
    op.create_index('ix_payment_merchant_id', 'payments', ['merchant_id'], unique=False)
    op.create_index('ix_payment_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payment_timestamp', 'payments', ['payment_timestamp'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('matched_records', sa.Integer(), nullable=False),
    sa.Column('unmatched_records', sa.Integer(), nullable=False),
    sa.Column('exceptions_found', sa.Integer(), nullable=False),
    sa.Column('auto_resolved', sa.Integer(), nullable=False),
    sa.Column('human_review', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('payment_source_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('speed', sa.String(), nullable=True),
    sa.Column('refund_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_system', name='uix_refund_source')
    )
    op.create_table('settlements',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tax', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('utr', sa.String(), nullable=True),
    sa.Column('settlement_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_system', name='uix_settlement_source')
    )
    op.create_table('evaluation_runs',
    sa.Column('reconciliation_run_id', sa.Uuid(), nullable=True),
    sa.Column('dataset_name', sa.String(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matching_precision', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('matching_recall', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('matching_f1', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('false_match_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('unresolved_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('exception_classification_accuracy', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('auto_resolution_precision', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('human_review_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_matches',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('refund_id', sa.Uuid(), nullable=True),
    sa.Column('chargeback_id', sa.Uuid(), nullable=True),
    sa.Column('ledger_entry_id', sa.Uuid(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('variance', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('recon_status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chargeback_id'], ['chargebacks.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exceptions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('exception_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount_involved', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('variance', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('policy_result', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['reconciliation_matches.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('decision_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_evidence', sa.JSON(), nullable=False),
    sa.Column('policy_evaluation', sa.JSON(), nullable=False),
    sa.Column('ai_recommendation', sa.JSON(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=False),
    sa.Column('after_state', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exception_evidence',
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exception_evidence')
    op.drop_table('decisions')
    op.drop_table('exceptions')
    op.drop_table('reconciliation_matches')
    op.drop_table('evaluation_runs')
    op.drop_table('settlements')
    op.drop_table('refunds')
    op.drop_table('reconciliation_runs')
    op.drop_index('ix_payment_timestamp', table_name='payments')
    op.drop_index('ix_payment_status', table_name='payments')
    op.drop_index('ix_payment_merchant_id', table_name='payments')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('ledger_entries')
    op.drop_table('invoices')
    op.drop_table('chargebacks')
    op.drop_table('merchants')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
